### ISSUE TITLE
Air Purifier Core 200S does not show up

### ISSUE THREAD

**Issue by Lykos153** [vlebourl/custom_vesync#16]
It does show up correctly in the core integration. How can I debug this?

**Comment by vlebourl** [comment]
I need to compare the codes to see what's missing here.

**Comment by vlebourl** [comment]
If you have any proficiency in python, feel free to have a look and help :)

**Comment by suth** [comment]
My Core 200S (the `LAP-C201S-AUSR` variety) is not appearing in either the core integration or this, but was able to successfully discover and control it using pyvesync directly on another machine.

Edit to include error log:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172 
First occurred: 4:06:45 PM (6 occurrences) 
Last logged: 4:06:45 PM

Error unloading entry ***@***.com for fan
Error unloading entry ***@***.com for light
Error unloading entry ***@***.com for sensor
Error unloading entry ***@***.com for number
Error unloading entry ***@***.com for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 87, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by vlebourl** [comment]
Issue grouped with #15 and #18 in #19.

**Comment by vlebourl** [comment]
is this still an issue?
