### ISSUE TITLE
Support fans

### ISSUE THREAD

**Issue by vlebourl** [vlebourl/custom_vesync#19]
It seems that fans aren't discovered properly.

- [x] #15
- [x] #16 
- [x] #18

**Comment by vlebourl** [comment]
a good starting point: https://github.com/vlebourl/custom_vesync/issues/15#issuecomment-1094039630

**Comment by vlebourl** [comment]
I added diagnostics in version v0.1.3.
Could you download them and add it here so I could try to understand why the fans aren't discovered correctly?

**Comment by kasper79** [comment]
This error originated from a custom integration.

Logger: custom_components.vesync.fan
Source: custom_components/vesync/fan.py:62
Integration: VeSync
First occurred: 7:48:19 AM (1 occurrences)
Last logged: 7:48:19 AM

Game Room - Unknown device type - LAP-C601S-WUS

This is a Core 600s (Air Purifier)
I enabled DEBUG in the log, doesn't look to show much else on this error.

**Comment by vlebourl** [comment]
Could you go into the integration page, download the diagnostics, and paste here the part relevant to vesync (see [help](https://www.home-assistant.io/integrations/diagnostics/) if needed)?  
It should something like this: 
```json
  "data": {
    "fans": [
      {
        "device": {
          "module": "VeSyncHumid200300S",
          "models": [
            "Dual200S",
            "LUH-D301S-WUSR",
            "LUH-D301S-WJP",
            "LUH-D301S-WEU"
          ],
          "features": [],
          "mist_modes": [
            "auto",
            "manual"
          ],
          "mist_levels": [
            1,
            2
          ]
        },
        "config": {
          "auto_target_humidity": 60,
          "display": true,
          "automatic_stop": true
        },
        "details": {
          "humidity": 58,
          "mist_virtual_level": 1,
          "mist_level": 1,
          "mode": "manual",
          "water_lacks": false,
          "humidity_high": false,
          "water_tank_lifted": false,
          "display": false,
          "automatic_stop_reach_target": false
        }
      }
    ],
    "outlets": [],
    "switches": [],
    "bulbs": []
  }
  ```

**Comment by vlebourl** [comment]
Could you try branch [fix/fix-fan-discovery](https://github.com/vlebourl/custom_vesync/tree/fix/fix-fan-discovery) and report whether that fixes the fan discovery?

**Comment by kasper79** [comment]
The device shows up now, but no entity (fan)
![image](https://user-images.githubusercontent.com/13425376/165308129-17557e5e-e208-4443-932b-6681fe8cb734.png)

I've tried to download the diagnostics, but maybe i've done something wrong? It tells me either "Server Error" or " Unauthorized" when trying to download the file

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/vesync/diagnostics.py:21
Integration: VeSync
First occurred: 8:13:49 AM (2 occurrences)
Last logged: 8:13:54 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 211, in get
    data = await info[d_type.value](hass, config_entry)
  File "/config/custom_components/vesync/diagnostics.py", line 21, in async_get_config_entry_diagnostics
    {"device": d.config_dict, "config": d.config, "details": d.details}
AttributeError: 'VeSyncAir131' object has no attribute 'config_dict'

**Comment by vlebourl** [comment]
diagnistics is fixed.

**Comment by kasper79** [comment]
Same issue with diagnostics - sorry! 
Saw this as well:
Logger: homeassistant.components.fan
Source: custom_components/vesync/fan.py:101
Integration: Fan (documentation, issues)
First occurred: 8:48:42 AM (2 occurrences)
Last logged: 8:48:42 AM

Error adding entities for domain fan with platform vesync
Error while setting up vesync platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 320, in capability_attributes
    attrs[ATTR_PRESET_MODES] = self.preset_modes
  File "/config/custom_components/vesync/fan.py", line 101, in preset_modes
    return PRESET_MODES[self.device.device_type]
KeyError: 'LAP-C601S-WUS'


and:

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/vesync/diagnostics.py:22
Integration: VeSync
First occurred: 8:49:43 AM (5 occurrences)
Last logged: 8:58:25 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 211, in get
    data = await info[d_type.value](hass, config_entry)
  File "/config/custom_components/vesync/diagnostics.py", line 22, in async_get_config_entry_diagnostics
    "device": d.config_dict or {},
AttributeError: 'VeSyncAir131' object has no attribute 'config_dict'

**Comment by vlebourl** [comment]
can we move the discussion to the PR? #21
