### ISSUE TITLE
No longer able to control

### ISSUE THREAD

**Issue by sbelongie** [vlebourl/custom_vesync#26]
### The problem

Updated to 0.1.6 and all my attributes went away.  I rolled everything back and everything was back to normal.

Pre update
preset_modes:
  - sleep
percentage: null
percentage_step: 33.333333333333336
preset_mode: sleep
screen_status: false
child_lock: false
night_light: 'off'
air_quality: 0
mode: sleep
filter_life: 98
friendly_name: 'fan name '
supported_features: 1

after

restored: true
preset_modes:
  - sleep
friendly_name: 'fan name '
supported_features: 1

### What version of this integration has the issue?

0.1.6

### What version of Home Assistant Core has the issue?

2022.6.4

**Comment by vlebourl** [comment]
oups... 
Stupid mistake, should be fixed in https://github.com/vlebourl/custom_vesync/commit/93bc99834246eaf95b41c19b8cb47e6d357f1b91
and 0.1.7

**Comment by hanley-development** [comment]
looks like the we're getting another issue:

```py
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration vesync: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 747, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/vesync/__init__.py", line 11, in <module>
from .common import async_process_devices
File "/config/custom_components/vesync/common.py", line 5, in <module>
from pyvesync.vesyncfan import model_features
ImportError: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 223, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 754, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration vesync: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
```

**Comment by vlebourl** [comment]
Thank you, could you open a new issue with this one as it's not related to the thread. 
Cheers
