### ISSUE TITLE
Cannot import name 'model_features' from 'pyvesync.vesyncfan'

### ISSUE THREAD

**Issue by hanley-development** [vlebourl/custom_vesync#27]
### The problem

Unable to load integration:

```py
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration vesync: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 747, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/vesync/__init__.py", line 11, in <module>
from .common import async_process_devices
File "/config/custom_components/vesync/common.py", line 5, in <module>
from pyvesync.vesyncfan import model_features
ImportError: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 223, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 754, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration vesync: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
```

### What version of this integration has the issue?

0.1.7

### What version of Home Assistant Core has the issue?

core-2022.6.4

### Diagnostics

Not Loaded

### Home Assistant log

<details><summary>Logs</summary>

```py
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration vesync: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 747, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/vesync/__init__.py", line 11, in <module>
from .common import async_process_devices
File "/config/custom_components/vesync/common.py", line 5, in <module>
from pyvesync.vesyncfan import model_features
ImportError: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 223, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 754, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2022-06-09 13:45:28 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration vesync: cannot import name 'model_features' from 'pyvesync.vesyncfan' (/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py)```
</details>


### Additional information

_No response_

**Comment by vlebourl** [comment]
I'm not sure why this happens. This version moved back to the external dependency on pyvesync, this might cause the issue if it did not install correctly. Could you try removing the custom integration from your HACS repo, restart Home Assistant, and reinstall custom vesync? That way, it should enforce complete installation of the integration and it's dependencies.

**Comment by vlebourl** [comment]
Of course Home Assistant needs restarting after the custom component installation.

**Comment by hanley-development** [comment]
1. Had to downgrade to 0.1.5. Integration would not uninstall since it was in a starting state.
2. Uninstalled integration
3. restarted HomeAssistant
4. Uninstalled from HACS
5. restarted HomeAssistant
6. Confirmed directory was removed from custom_components
7. downloaded with HACs
8. restarted HomeAssistant
9. Tried to run through setup
```
Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```

**Comment by vlebourl** [comment]
Damn... I have no idea... 😥

**Comment by vlebourl** [comment]
I haven't been able to reproduce this... My take is it's a corrupted installation that messed up the dependency on pyvesync. Appart from a full reinstall, I have no real idea... If you install version 0.1.5 you should be back on the local dependency on pyvesync that should avoid this error. There is no real difference with current version. Maybe some attributes, but nothing major.

**Comment by hanley-development** [comment]
version 0.1.5 installed:
```
 /config # pip show pyvesync
Name: pyvesync
Version: 1.4.3
Summary: pyvesync is a library to manage Etekcity                 Devices and Levoit Air Purifier
Home-page: https://github.com/markperdue/pyvesync
Author: Mark Perdue, Joe Trabulsy
Author-email: webdjoe@gmail.com
License: MIT
```

version 0.1.7 installed:
```
 /config # pip show pyvesync
Name: pyvesync
Version: 1.4.3
Summary: pyvesync is a library to manage Etekcity                 Devices and Levoit Air Purifier
Home-page: https://github.com/markperdue/pyvesync
Author: Mark Perdue, Joe Trabulsy
Author-email: webdjoe@gmail.com
License: MIT
```

**Comment by hanley-development** [comment]
```
/config # pip show pyvesync
Name: pyvesync
Version: 1.4.3
Summary: pyvesync is a library to manage Etekcity                 Devices and Levoit Air Purifier
Home-page: https://github.com/markperdue/pyvesync
Author: Mark Perdue, Joe Trabulsy
Author-email: webdjoe@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: requests
Required-by:
/config # exit
➜  ~ ha core rebuild
Processing... Done.

Command completed successfully.
➜  ~ docker exec -it homeassistant sh
/config # pip show pyvesync
Name: pyvesync
Version: 2.0.3
Summary: pyvesync is a library to manage Etekcity                 Devices and Levoit Air Purifier
Home-page: https://github.com/webdjoe/pyvesync
Author: Mark Perdue, Joe Trabulsy
Author-email: webdjoe@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: requests
Required-by:
/config #

```

**Comment by hanley-development** [comment]
I was able to fix the dependency issue with a core rebuild. THANK YOU @vlebourl!

**Comment by vlebourl** [comment]
Nice! 
Sorry I couldn't help more.

**Comment by hanley-development** [comment]
Oh you did more than you needed to! This was a system issue, not the integration. I need to investigate why python packages didnt update with the last update. #https://github.com/home-assistant/core/pull/71771
