### ISSUE TITLE
Warm Mist attributes not detected

### ISSUE THREAD

**Issue by nonamejuju** [vlebourl/custom_vesync#28]
### The problem

Hello I'm having a LUH-A602S-WEU, everything is working great but the Warm Mist related entities are not detected : warm_mist_level & warm_mist_enabled

### What version of this integration has the issue?

0.1.7

### What version of Home Assistant Core has the issue?

core-2022.6.5

### Diagnostics

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.6.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.15.41",
    "supervisor": "2022.05.3",
    "host_os": "Home Assistant OS 8.1",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "circadian_lighting": {
      "version": "2.0.8",
      "requirements": []
    },
    "variable": {
      "version": "2.2.2",
      "requirements": []
    },
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "spotcast": {
      "version": "v3.6.29",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    },
    "deebot": {
      "version": "1.3.1",
      "requirements": [
        "deebot-client==1.4.0",
        "numpy>=1.21.2"
      ]
    },
    "vesync": {
      "version": "0.1.3",
      "requirements": []
    },
    "adaptive_lighting": {
      "version": "1.0.14",
      "requirements": []
    },
    "livebox": {
      "version": "1.7.6",
      "requirements": [
        "aiosysbus==0.2.0"
      ]
    },
    "localtuya": {
      "version": "3.2.1",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "iot_class": "cloud_polling",
    "version": "0.1.3",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "fans": [
      {
        "config_dict": {
          "module": "VeSyncHumid200300S",
          "models": [
            "LUH-A602S-WUSR",
            "LUH-A602S-WUS",
            "LUH-A602S-WEUR",
            "LUH-A602S-WEU",
            "LUH-A602S-WJP"
          ],
          "features": [
            "warm_mist",
            "nightlight"
          ],
          "mist_modes": [
            "humidity",
            "sleep",
            "manual"
          ],
          "mist_levels": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
          ],
          "warm_mist_levels": [
            0,
            1,
            2,
            3
          ]
        },
        "config": {
          "auto_target_humidity": 80,
          "display": false,
          "automatic_stop": true
        },
        "details": {
          "humidity": 51,
          "mist_virtual_level": 9,
          "mist_level": 3,
          "mode": "humidity",
          "water_lacks": false,
          "humidity_high": false,
          "water_tank_lifted": false,
          "display": false,
          "automatic_stop_reach_target": false,
          "night_light_brightness": 0,
          "warm_mist_level": 0,
          "warm_mist_enabled": false
        }
      }
    ],
    "outlets": [],
    "switches": [],
    "bulbs": []
  }
}

### Home Assistant log

<details><summary>Logs</summary>

```py


2022-06-13 20:37:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration variable which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration vesync which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration livebox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-13 20:37:32 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for localtuya using this method at custom_components/localtuya/__init__.py, line 315: ent_reg = await er.async_get_registry(hass)
2022-06-13 20:37:32 WARNING (MainThread) [homeassistant.components.spotify] The 'spotify' option near /config/configuration.yaml:1 is deprecated, please remove it from your configuration
2022-06-13 20:37:32 WARNING (MainThread) [homeassistant.components.spotify] Configuration of Spotify integration in YAML is deprecated and will be removed in a future release; Your existing OAuth Application Credentials have been imported into the UI automatically and can be safely removed from your configuration.yaml file
2022-06-13 20:37:38 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for livebox using this method at custom_components/livebox/__init__.py, line 77: device_registry = await dr.async_get_registry(hass)
2022-06-13 20:37:53 WARNING (MainThread) [deebot_client.commands.common] Command "getPos" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:08 WARNING (MainThread) [deebot_client.commands.common] Command "getStats" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:08 WARNING (MainThread) [deebot_client.commands.common] Command "getChargeState" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:23 WARNING (MainThread) [deebot_client.commands.common] Command "getCleanInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:23 WARNING (MainThread) [deebot_client.commands.common] Command "getWaterInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:23 WARNING (MainThread) [deebot_client.commands.common] Command "getVolume" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/deebot_client/events/event_bus.py", line 139, in _call_refresh_function
await self._execute_command(commands[0])
File "/usr/local/lib/python3.9/site-packages/deebot_client/vacuum_bot.py", line 111, in execute_command
result = command.handle_requested(self.events, response)
File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/clean_logs.py", line 38, in handle_requested
stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'
2022-06-13 20:38:38 WARNING (MainThread) [deebot_client.commands.common] Command "getLifeSpan" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:38 WARNING (MainThread) [deebot_client.commands.common] Command "getError" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:38 WARNING (MainThread) [deebot_client.commands.common] Command "getTotalStats" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:53 WARNING (MainThread) [deebot_client.commands.common] Command "getAdvancedMode" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:53 WARNING (MainThread) [deebot_client.commands.common] Command "getBreakPoint" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:38:54 WARNING (MainThread) [deebot_client.commands.common] Command "getCarpertPressure" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:39:08 WARNING (MainThread) [deebot_client.commands.common] Command "getBattery" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:39:08 WARNING (MainThread) [deebot_client.commands.common] Command "getSpeed" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:39:09 WARNING (MainThread) [deebot_client.commands.common] Command "getCachedMapInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:39:23 WARNING (MainThread) [deebot_client.commands.common] Command "getCachedMapInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:39:23 WARNING (MainThread) [deebot_client.commands.common] Command "getMapTrace" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2022-06-13 20:39:24 WARNING (MainThread) [deebot_client.commands.common] Command "getMajorMap" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}```

</details>


### Additional information

_No response_

**Comment by vlebourl** [comment]
Hi, 
thanks for the report!
Could you try the branch in PR #29?

**Comment by nonamejuju** [comment]
Hello Vincent, thanks for the quick patch, unfortunatly it doesn't seems to work, after instalation I even lost 2 entities: 
![image](https://user-images.githubusercontent.com/11179057/173565305-24552f0a-7ec2-4480-89dd-2fae648e0fb4.png)

**Comment by vlebourl** [comment]
Seems like I messed it up... It might be tough to implement without access to the device...
Would you mind joining on discord so we can discuss further, and maybe give me temporary access to your device? 
https://discord.gg/KTZrBKq7

**Comment by vlebourl** [comment]
Hi, could you confirm the branch in PR #29 works for you so I can merge and close?
Cheers.

V.

**Comment by nonamejuju** [comment]
Hello ! It seems the direct mail response didn't work when I replied to you so I will confirm here also that it is workings perfectly and that you can merge :)

Have a nice day !

**Comment by nonamejuju** [comment]
Hello Vincent, yes I can confirm it is working very well indeed.
You can merge and close ;)

Have a nice day !

Julien Hondaâ
3D Lighter, Generalist & Trainer
