### ISSUE TITLE
Devices missing fan speed, child lock, and night light entities and manual mode preset after 0.1.11 to 0.1.12 upgrade.

### ISSUE THREAD

**Issue by hanley-development** [vlebourl/custom_vesync#41]
### The problem

Devices missing fan speed, child lock, and night light entities and manual mode preset after 0.1.11 to 0.1.12 upgrade.

### What version of this integration has the issue?

0.1.12

### What version of Home Assistant Core has the issue?

core-2022.7.7

### Diagnostics

```json
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "iot_class": "cloud_polling",
    "version": "0.1.3",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "fans": [
      {
        "config_dict": {
          "module": "VeSyncAirBypass",
          "models": [
            "Core600S",
            "LAP-C601S-WUS",
            "LAP-C601S-WUSR",
            "LAP-C601S-WEU"
          ],
          "modes": [
            "sleep",
            "off",
            "auto"
          ],
          "features": [
            "air_quality"
          ],
          "levels": [
            1,
            2,
            3,
            4
          ]
        },
        "config": {
          "display": false,
          "display_forever": true
        },
        "details": {
          "filter_life": 89,
          "mode": "manual",
          "level": 0,
          "display": false,
          "child_lock": false,
          "night_light": "off",
          "air_quality": 1,
          "display_forever": false,
          "air_quality_value": 1
        }
      },
      {
        "config_dict": {
          "module": "VeSyncAirBypass",
          "models": [
            "Core300S",
            "LAP-C301S-WJP"
          ],
          "modes": [
            "sleep",
            "off",
            "auto"
          ],
          "features": [
            "air_quality"
          ],
          "levels": [
            1,
            2,
            3,
            4
          ]
        },
        "config": {
          "display": true,
          "display_forever": true
        },
        "details": {
          "filter_life": 31,
          "mode": "manual",
          "level": 0,
          "display": true,
          "child_lock": false,
          "night_light": "off",
          "air_quality": 1,
          "display_forever": false,
          "air_quality_value": 1
        }
      },
      {
        "config_dict": {
          "module": "VeSyncAirBypass",
          "models": [
            "Core300S",
            "LAP-C301S-WJP"
          ],
          "modes": [
            "sleep",
            "off",
            "auto"
          ],
          "features": [
            "air_quality"
          ],
          "levels": [
            1,
            2,
            3,
            4
          ]
        },
        "config": {
          "display": true,
          "display_forever": true
        },
        "details": {
          "filter_life": 92,
          "mode": "manual",
          "level": 0,
          "display": false,
          "child_lock": false,
          "night_light": "off",
          "air_quality": 1,
          "display_forever": false,
          "air_quality_value": 1
        }
      }
    ],
    "outlets": [],
    "switches": [],
    "bulbs": []
  }
```

### Home Assistant log

<details><summary>Logs</summary>

```py
2022-08-02 23:23:59 DEBUG (SyncWorker_5) [pyvesync.vesync] New device list initialized
2022-08-02 23:23:59 DEBUG (SyncWorker_5) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:23:59 DEBUG (SyncWorker_5) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:00 DEBUG (SyncWorker_5) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:02 DEBUG (MainThread) [custom_components.vesync.common] Found a fan: {'manager': <pyvesync.vesync.VeSync object at 0x7fd66b8cdf30>, 'device_name': 'Living Room Air Purifier', 'device_image': 'https://image.vesync.com/defaultImages/deviceDefaultImages/wfon_apr_lap-c601s-wus_us_240.png', 'cid': 'vsaqae46d6434c3b989ba234666899b3', 'connection_status': 'online', 'connection_type': 'WiFi+BTOnboarding+BTNotify', 'device_type': 'LAP-C601S-WUS', 'type': 'wifi-air', 'uuid': '38c3c4be-abf4-4a6f-9a14-febd6faefff2', 'config_module': 'WFON_APR_LAP-C601S-WUS_US', 'mac_id': '78:e3:6d:34:80:9e', 'mode': 'sleep', 'speed': 1, 'extension': {'airQuality': -1, 'airQualityLevel': 1, 'mode': 'sleep', 'fanSpeedLevel': '1'}, 'current_firm_version': None, 'sub_device_no': None, 'config': {'display': False, 'display_forever': True}, 'device_status': 'on', 'enabled': True, 'config_dict': {'module': 'VeSyncAirBypass', 'models': ['Core600S', 'LAP-C601S-WUS', 'LAP-C601S-WUSR', 'LAP-C601S-WEU'], 'modes': ['sleep', 'off', 'auto'], 'features': ['air_quality'], 'levels': [1, 2, 3, 4]}, 'features': ['air_quality'], 'modes': ['sleep', 'off', 'auto'], 'air_quality_feature': True, 'details': {'filter_life': 89, 'mode': 'manual', 'level': 0, 'display': False, 'child_lock': False, 'night_light': 'off', 'air_quality': 1, 'display_forever': False, 'air_quality_value': 1}}
2022-08-02 23:24:02 DEBUG (MainThread) [custom_components.vesync.common] Found a fan: {'manager': <pyvesync.vesync.VeSync object at 0x7fd66b8cdf30>, 'device_name': 'Office of Mike Core 300s', 'device_image': 'https://image.vesync.com/defaultImages/Core_300S_Series/icon_300_purifier_160.png', 'cid': 'vsaqb2549d084efd8c8943da11c045f7', 'connection_status': 'online', 'connection_type': 'WiFi+BTOnboarding+BTNotify', 'device_type': 'Core300S', 'type': 'wifi-air', 'uuid': '458f0df8-6ca5-4dad-a54a-bf6d8861af42', 'config_module': 'WiFiBTOnboardingNotify_AirPurifier_Core300S_US', 'mac_id': 'c4:5b:be:bd:79:2e', 'mode': 'auto', 'speed': 2, 'extension': {'airQuality': -1, 'airQualityLevel': 1, 'mode': 'auto', 'fanSpeedLevel': '1'}, 'current_firm_version': None, 'sub_device_no': None, 'config': {'display': True, 'display_forever': True}, 'device_status': 'on', 'enabled': True, 'config_dict': {'module': 'VeSyncAirBypass', 'models': ['Core300S', 'LAP-C301S-WJP'], 'modes': ['sleep', 'off', 'auto'], 'features': ['air_quality'], 'levels': [1, 2, 3, 4]}, 'features': ['air_quality'], 'modes': ['sleep', 'off', 'auto'], 'air_quality_feature': True, 'details': {'filter_life': 31, 'mode': 'manual', 'level': 0, 'display': True, 'child_lock': False, 'night_light': 'off', 'air_quality': 1, 'display_forever': False, 'air_quality_value': 1}}
2022-08-02 23:24:02 DEBUG (MainThread) [custom_components.vesync.common] Found a fan: {'manager': <pyvesync.vesync.VeSync object at 0x7fd66b8cdf30>, 'device_name': 'Master Bedroom Air Purifier', 'device_image': 'https://image.vesync.com/defaultImages/Core_300S_Series/icon_300_purifier_160.png', 'cid': 'vsaq684c8bdb411ab81337a915deed4c', 'connection_status': 'online', 'connection_type': 'WiFi+BTOnboarding+BTNotify', 'device_type': 'Core300S', 'type': 'wifi-air', 'uuid': '510743f8-9f5b-4a10-be4b-c612ef4c1b99', 'config_module': 'WiFiBTOnboardingNotify_AirPurifier_Core300S_US', 'mac_id': 'c4:5b:be:bc:bf:8e', 'mode': 'sleep', 'speed': 2, 'extension': {'airQuality': -1, 'airQualityLevel': 1, 'mode': 'sleep', 'fanSpeedLevel': '1'}, 'current_firm_version': None, 'sub_device_no': None, 'config': {'display': True, 'display_forever': True}, 'device_status': 'on', 'enabled': True, 'config_dict': {'module': 'VeSyncAirBypass', 'models': ['Core300S', 'LAP-C301S-WJP'], 'modes': ['sleep', 'off', 'auto'], 'features': ['air_quality'], 'levels': [1, 2, 3, 4]}, 'features': ['air_quality'], 'modes': ['sleep', 'off', 'auto'], 'air_quality_feature': True, 'details': {'filter_life': 92, 'mode': 'manual', 'level': 0, 'display': False, 'child_lock': False, 'night_light': 'off', 'air_quality': 1, 'display_forever': False, 'air_quality_value': 1}}
2022-08-02 23:24:02 INFO (MainThread) [custom_components.vesync.common] 3 VeSync fans found
2022-08-02 23:24:02 DEBUG (MainThread) [custom_components.vesync.fan] Adding device Living Room Air Purifier LAP-C601S-WUS
2022-08-02 23:24:02 DEBUG (MainThread) [custom_components.vesync.fan] Adding device Office of Mike Core 300s Core300S
2022-08-02 23:24:02 DEBUG (MainThread) [custom_components.vesync.fan] Adding device Master Bedroom Air Purifier Core300S
2022-08-02 23:24:02 DEBUG (SyncWorker_2) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:02 DEBUG (SyncWorker_3) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:02 DEBUG (SyncWorker_0) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:02 DEBUG (SyncWorker_5) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:03 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform vesync
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 437, in _async_add_entity
entity.add_to_platform_start(
AttributeError: 'tuple' object has no attribute 'add_to_platform_start'
2022-08-02 23:24:03 ERROR (MainThread) [homeassistant.components.number] Error while setting up vesync platform for number
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 437, in _async_add_entity
entity.add_to_platform_start(
AttributeError: 'tuple' object has no attribute 'add_to_platform_start'
2022-08-02 23:24:03 DEBUG (SyncWorker_3) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:03 DEBUG (SyncWorker_2) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:03 DEBUG (SyncWorker_5) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:03 DEBUG (SyncWorker_4) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:03 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform vesync
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 969, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/vesync/light.py", line 229, in is_on
return self.smarthumidifier.details["night_light_brightness"] > 0
KeyError: 'night_light_brightness'
2022-08-02 23:24:03 ERROR (MainThread) [homeassistant.components.light] Error while setting up vesync platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 969, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/vesync/light.py", line 229, in is_on
return self.smarthumidifier.details["night_light_brightness"] > 0
KeyError: 'night_light_brightness'
2022-08-02 23:24:04 DEBUG (SyncWorker_0) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:04 DEBUG (SyncWorker_1) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:04 DEBUG (SyncWorker_5) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:04 DEBUG (SyncWorker_2) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:04 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform vesync
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 969, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/vesync/switch.py", line 134, in is_on
return self.device.details["child_locked"]
KeyError: 'child_locked'
2022-08-02 23:24:04 ERROR (MainThread) [homeassistant.components.switch] Error while setting up vesync platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 969, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/vesync/switch.py", line 134, in is_on
return self.device.details["child_locked"]
KeyError: 'child_locked'
2022-08-02 23:24:04 DEBUG (SyncWorker_7) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:05 DEBUG (SyncWorker_8) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:05 DEBUG (SyncWorker_0) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:05 DEBUG (SyncWorker_6) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:06 DEBUG (SyncWorker_0) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:24:06 DEBUG (SyncWorker_6) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:16 DEBUG (SyncWorker_17) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:17 DEBUG (SyncWorker_18) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:24 DEBUG (SyncWorker_14) [pyvesync.vesyncfan] Office of Mike Core 300s does not have manual mode
2022-08-02 23:51:24 DEBUG (SyncWorker_38) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:28 DEBUG (SyncWorker_19) [pyvesync.vesyncfan] Office of Mike Core 300s does not have manual mode
2022-08-02 23:51:28 DEBUG (SyncWorker_2) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:35 DEBUG (SyncWorker_39) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:35 DEBUG (SyncWorker_7) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:36 DEBUG (SyncWorker_37) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:37 DEBUG (SyncWorker_34) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:37 DEBUG (SyncWorker_25) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:37 DEBUG (SyncWorker_18) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:38 DEBUG (SyncWorker_11) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:38 DEBUG (SyncWorker_36) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2022-08-02 23:51:38 DEBUG (SyncWorker_27) [pyvesync.helpers] [post] calling '/cloud/v2/deviceManaged/bypassV2' api
```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/99109069/182526589-e05c5b92-1cb7-45df-ba5e-ee76716e3495.png)

![image](https://user-images.githubusercontent.com/99109069/182526396-03a0bbef-f358-4f35-a3ca-c4b889f16b31.png)

**Comment by hanley-development** [comment]
### Reverted to 0.1.11:
![image](https://user-images.githubusercontent.com/99109069/182538282-86c78869-e92d-45c6-a544-30640c7e71a2.png)

![image](https://user-images.githubusercontent.com/99109069/182537914-6499f448-dcd6-4c7d-ad68-b16cd54a2150.png)

![image](https://user-images.githubusercontent.com/99109069/182538428-09740b10-9d93-48b3-af8d-747fdb97ca42.png)
